force-app/main/default/objects/Field_Mapping__c/Field_Mapping__c.object-meta.xml
<CustomObject>
    <label>Field Mapping</label>
    <nameField>
        <displayFormat>FM-{0000000}</displayFormat>
        <label>Field Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Field Mappings</pluralLabel>
    <!---->
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Field_Mappings__mdt/fields/NetSuite_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_Field_API_Name__c</fullName>
    <label>NetSuite Field API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Mappings__mdt/fields/Object_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Object_Mapping__c</fullName>
    <label>Object Mapping</label>
    <referenceTo>Object_Mapping__mdt</referenceTo>
    <relationshipLabel>Field Mappings</relationshipLabel>
    <relationshipName>Field_Mappings</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Field_Mappings__mdt/fields/SFDC_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>SFDC_Field_API_Name__c</fullName>
    <label>SFDC Field API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Object_Mapping__mdt/Object_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>Object Mapping</label>
    <pluralLabel>Object Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Object_Mapping__mdt/fields/JSON_SObject_Name__c.field-meta.xml
<CustomField>
    <fullName>JSON_SObject_Name__c</fullName>
    <label>JSON SObject Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Object_Mapping__mdt/fields/Parent_Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Parent_Object_Name__c</fullName>
    <label>Parent Object Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Object_Mapping__mdt/fields/Relationship_Type__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Type__c</fullName>
    <label>Relationship Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Object_Mapping__mdt/fields/Relationship_with_Parent__c.field-meta.xml
<CustomField>
    <fullName>Relationship_with_Parent__c</fullName>
    <label>Relationship with Parent</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SObject_Mapping__c/SObject_Mapping__c.object-meta.xml
<CustomObject>
    <label>JSON Mapping</label>
    <nameField>
        <label>SObject Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>JSON Mapping</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SObject_Mapping__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>True: to sync records of the object mentioned in SObject Name using Netsuite Connector App.
False: to stop sync records of the object mentioned in SObject Name using Netsuite Connector App.</inlineHelpText>
    <label>IsActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SObject_Mapping__c/fields/JSON_Sobject_Name__c.field-meta.xml
<CustomField>
    <fullName>JSON_Sobject_Name__c</fullName>
    <inlineHelpText>Required. SObject identifier in the NetSuite.</inlineHelpText>
    <label>JSON SObject Name</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/SObject_Mapping__c/fields/Parent_SObject_Map__c.field-meta.xml
<CustomField>
    <fullName>Parent_SObject_Map__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Required for child Relationship Type.
Lookup to parent object.</inlineHelpText>
    <label>Parent SObject Map</label>
    <referenceTo>SObject_Mapping__c</referenceTo>
    <relationshipLabel>SObject Mapping</relationshipLabel>
    <relationshipName>SObject_Mappings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SObject_Mapping__c/fields/Relationship_Type__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Type__c</fullName>
    <inlineHelpText>Parent: use for parent object. E.g. Opportunity
Child: use for child object. E.g. OpportunityContactRole / OpportunityLineItem</inlineHelpText>
    <label>Relationship Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Parent</fullName>
            </value>
            <value>
                <fullName>Child</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SObject_Mapping__c/fields/Relationship_with_parent__c.field-meta.xml
<CustomField>
    <fullName>Relationship_with_parent__c</fullName>
    <inlineHelpText>Required for child Relationship Type. 
API name of the parent object relationship field (Lookup / Master-Details) on object mentioned in Parent SObject Mapping field. 
E.g. If SObject Name is OpportunityLineItem then OpportunityId or any other custom lookup or master detail field referencing Opportunity.</inlineHelpText>
    <label>Relationship with parent</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/GenerateSObjectFieldMapping.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 04-03-2024
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public with sharing class GenerateSObjectFieldMapping {

    /**
    * @description : Insert predefined data in Object Mapping and Field Mapping 
    * @author ChangeMeIn@UserSettingsUnder.SFDoc | 04-03-2024 
    **/
    @InvocableMethod(label='Create Object Mapping' description='description')
    public static void insertObjectFieldMapping() 
    {
        Map<String,SObject_Mapping__c> objsMap = new Map<String,SObject_Mapping__c>();
        Map<String,SObject_Mapping__c> childObjsMap = new Map<String,SObject_Mapping__c>();
        List<Field_Mapping__c> fieldMapList = new List<Field_Mapping__c>();
        List<Field_Mapping__c> childFieldMapList = new List<Field_Mapping__c>();
        for(Field_Mappings__mdt fieldMdt : [SELECT Id,Label,Field_Type__c,NetSuite_Field_API_Name__c,SFDC_Field_API_Name__c,
                                                   Object_Mapping__r.Id,Object_Mapping__r.Label,Object_Mapping__r.JSON_SObject_Name__c,Object_Mapping__r.Parent_Object_Name__c,Object_Mapping__r.Relationship_Type__c,Object_Mapping__r.Relationship_with_Parent__c 
                                            FROM Field_Mappings__mdt])
        {
            String objName = fieldMdt.Object_Mapping__r.Label;
            String parentObjName = fieldMdt.Object_Mapping__r.Parent_Object_Name__c;
            
            Field_Mapping__c fieldMap = new Field_Mapping__c(Field_Type__c = fieldMdt.Field_Type__c,
                                                             NetSuite_Field_API_Name__c =  fieldMdt.NetSuite_Field_API_Name__c,
                                                             SFDC_Field_API_Name__c =   fieldMdt.Label,
                                                             IsActive__c = true
                                                            );
            SObject_Mapping__c objMappingRef = new SObject_Mapping__c(External_ID__c = fieldMdt.Object_Mapping__r.Id);
            fieldMap.SObject_Mapping__r = objMappingRef;
            
            
            if(String.isNotBlank(parentObjName)){
                childFieldMapList.add(fieldMap);
            }else{
                fieldMapList.add(fieldMap);
            }
            
            if(!objsMap.containsKey(objName))
            {

                SObject_Mapping__c objMapping = new SObject_Mapping__c(External_ID__c = fieldMdt.Object_Mapping__r.Id,
                                                                       Name = fieldMdt.Object_Mapping__r.Label,
                                                                       JSON_SObject_Name__c = fieldMdt.Object_Mapping__r.JSON_SObject_Name__c,
                                                                       IsActive__c = true,
                                                                       Relationship_Type__c = fieldMdt.Object_Mapping__r.Relationship_Type__c,
                                                                       Relationship_with_parent__c = fieldMdt.Object_Mapping__r.Relationship_with_Parent__c
                                                                      );
               
                if(String.isNotBlank(parentObjName)){
                    childObjsMap.put(parentObjName,objMapping);
                    continue;
                }
                objsMap.put(objName,objMapping); 
            }
        }   
        
        if(!objsMap.isEmpty() && !fieldMapList.isEmpty()){
            
            // Insert Sobject mapping records
            insert objsMap.values();
            
            // Insert field mappings
            insert fieldMapList;
        }
        if(!childObjsMap.isEmpty()){
            for(String parentObj : childObjsMap.Keyset()){
                if(objsMap.containsKey(parentObj)){
                     SObject_Mapping__c objMapping = objsMap.get(parentObj);
                     SObject_Mapping__c parentobjMapping = childObjsMap.get(parentObj);
                     parentobjMapping.Parent_SObject_Map__c = objMapping.id;
                }
            }
            insert childObjsMap.values();

            insert childFieldMapList;
        }
    }
}