force-app/main/default/objects/NS_Connector_Logs__c/NS_Connector_Logs__c.object-meta.xml
<CustomObject>
    <label>Logs</label>
    <nameField>
        <displayFormat>Log - {000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NS_Connector_Logs__c/fields/Logging_Level__c.field-meta.xml
<CustomField>
    <fullName>Logging_Level__c</fullName>
    <label>Logging Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>INFO</fullName>
            </value>
            <value>
                <fullName>ERROR</fullName>
            </value>
            <value>
                <fullName>DEBUG</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NS_Connector_Logs__c/fields/NS_Sync_Request__c.field-meta.xml
<CustomField>
    <fullName>NS_Sync_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NS Sync Request</label>
    <referenceTo>NS_Sync_Request__c</referenceTo>
    <relationshipLabel>NS Sync Requests</relationshipLabel>
    <relationshipName>NS_Sync_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NS_Connector_Logs__c/fields/Source_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Source_Record_Id__c</fullName>
    <inlineHelpText>Id of the source object record for which error has occurred.</inlineHelpText>
    <label>Source Record Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NS_Sync_Request__c/NS_Sync_Request__c.object-meta.xml
<CustomObject>
    <label>Sync Request</label>
    <nameField>
        <displayFormat>NSR-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sync Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NS_Sync_Request__c/fields/Source_Object_Type__c.field-meta.xml
<CustomField>
    <fullName>Source_Object_Type__c</fullName>
    <description>Type of the record&apos;s object that needs to be synced E.g. Account, Order, Invoice etc....</description>
    <inlineHelpText>Type of the record&apos;s object that needs to be synced E.g. Account, Order, Invoice etc....</inlineHelpText>
    <label>Source Object Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NS_Sync_Request__c/fields/Source_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Source_Record_Id__c</fullName>
    <description>Id object the record that needs to be synced to Netsuite.</description>
    <inlineHelpText>Id object the record that needs to be synced to Netsuite.</inlineHelpText>
    <label>Source Record Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NS_Sync_Request__c/fields/Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>Sync_Status__c</fullName>
    <label>Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In-Progress</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
            </value>
            <value>
                <fullName>Queued</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
                <isActive>false</isActive>
                <label>Accepted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TriggerServiceHandler.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 03-18-2024
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public with sharing class TriggerServiceHandler {
    

    /**
    * @description : This is the common method for all the trigger services on specific objects  
    * @author ChangeMeIn@UserSettingsUnder.SFDoc | 02-21-2024 
    * @param sourceRec 
    * @return NS_Sync_Request__c 
    **/
    public NS_Sync_Request__c initNSSyncRequest(SObject sourceRec){
        Id sourceRecId = (Id)sourceRec.get('Id');
        String sourceRecordType = String.valueOf(sourceRec.getSObjectType());
        String sourceRecName = String.valueOf(sourceRec.get('Name'));

        return new NS_Sync_Request__c(
            Source_Record_Id__c = sourceRecId, 
            Source_Object_Type__c = sourceRecordType,
            Sync_Status__c = 'Queued'
            );
    }

    /**
    * @description 
    * @author ChangeMeIn@UserSettingsUnder.SFDoc | 03-04-2024 
    * @param syncReqList 
    **/
    public void creatNSSyncRequests(List<NS_Sync_Request__c> syncReqList)
    {
        List<NS_Connector_Logs__c> errorLogList = new List<NS_Connector_Logs__c>();
        //Insert NS Sync Requests-start
        List<Database.SaveResult> resultList = Database.insert(syncReqList,false);

        if(resultList != null && !resultList.isEmpty()){
            for(Integer i = 0; i < resultList.size();i++){
                if(!resultList[i].isSuccess()){
                    //log successfully inserted 
                    for(Database.Error err : resultList[i].getErrors()){
                        errorLogList.add(new NS_Connector_Logs__c(Component_Name__c ='TriggerServiceHandler:creatNSSyncRequests',
                        Error_Message__c = 'Object Type : '+syncReqList[i].Source_Object_Type__c +' Error : '+err.getMessage(),
                        Logging_Level__c = String.valueOf(LoggingLevel.ERROR),
                        Source_Record_Id__c = syncReqList[i].Source_Record_Id__c,
                        Timestamp__c = system.now()) );
                    }
                }
            }
        }

        if(!errorLogList.isEmpty()){
            insert errorLogList;
        }
        //Insert NS Sync Requests-end

    }
}