force-app/main/default/objects/NS_Sync_Request__c/NS_Sync_Request__c.object-meta.xml
<CustomObject>
    <label>Sync Request</label>
    <nameField>
        <displayFormat>NSR-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sync Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NS_Sync_Request__c/fields/CompletedDate__c.field-meta.xml
<CustomField>
    <fullName>CompletedDate__c</fullName>
    <label>CompletedDate</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/NS_Sync_Request__c/fields/ExtendedStatus__c.field-meta.xml
<CustomField>
    <fullName>ExtendedStatus__c</fullName>
    <label>ExtendedStatus</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NS_Sync_Request__c/fields/JobType__c.field-meta.xml
<CustomField>
    <fullName>JobType__c</fullName>
    <label>JobType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NS_Sync_Request__c/fields/LastProcessed__c.field-meta.xml
<CustomField>
    <fullName>LastProcessed__c</fullName>
    <label>LastProcessed</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NS_Sync_Request__c/fields/NumberOfErrors__c.field-meta.xml
<CustomField>
    <fullName>NumberOfErrors__c</fullName>
    <label>NumberOfErrors</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NS_Sync_Request__c/fields/Source_Object_Type__c.field-meta.xml
<CustomField>
    <fullName>Source_Object_Type__c</fullName>
    <description>Type of the record&apos;s object that needs to be synced E.g. Account, Order, Invoice etc....</description>
    <inlineHelpText>Type of the record&apos;s object that needs to be synced E.g. Account, Order, Invoice etc....</inlineHelpText>
    <label>Source Object Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NS_Sync_Request__c/fields/Source_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Source_Record_Id__c</fullName>
    <description>Id object the record that needs to be synced to Netsuite.</description>
    <inlineHelpText>Id object the record that needs to be synced to Netsuite.</inlineHelpText>
    <label>Source Record Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NS_Sync_Request__c/fields/Sync_Error__c.field-meta.xml
<CustomField>
    <fullName>Sync_Error__c</fullName>
    <label>Sync Error</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/NS_Sync_Request__c/fields/Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>Sync_Status__c</fullName>
    <label>Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In-Progress</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
            </value>
            <value>
                <fullName>Queued</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
                <isActive>false</isActive>
                <label>Accepted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NS_Sync_Request__c/fields/TotalJobItems__c.field-meta.xml
<CustomField>
    <fullName>TotalJobItems__c</fullName>
    <inlineHelpText>TotalJobItems process by batch apex</inlineHelpText>
    <label>TotalJobItems</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CustomNSSyncRequestIterable.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 03-14-2024
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public with sharing class CustomNSSyncRequestIterable implements Iterable<NS_Sync_Request__c> {
    public String objName = '';
    public List<NS_Sync_Request__c> syncRecList;
    public CustomNSSyncRequestIterable(String objName){
        this.objName = objName;
    }
    public CustomNSSyncRequestIterable(List<NS_Sync_Request__c> syncRecList){
        this.syncRecList = syncRecList;
    }
    public Iterator<NS_Sync_Request__c> iterator() {
        List<NS_Sync_Request__c> syncRequestList = new List<NS_Sync_Request__c>();
        if(String.isNotBlank( this.objName)){
            syncRequestList = [SELECT Id, Sync_Status__c, Sync_Error__c, Source_Record_Id__c, Source_Object_Type__c,Job_Status__c,NumberOfErrors__c,TotalJobItems__c,ExtendedStatus__c,CompletedDate__c,LastProcessed__c,JobType__c FROM NS_Sync_Request__c WHERE Sync_Status__c = 'Queued' AND Source_Object_Type__c =: this.objName];
        }else if(this.syncRecList != null && !this.syncRecList.isEmpty()){
            syncRequestList = [SELECT Id, Sync_Status__c, Sync_Error__c, Source_Record_Id__c, Source_Object_Type__c,Job_Status__c,NumberOfErrors__c,TotalJobItems__c,ExtendedStatus__c,CompletedDate__c,LastProcessed__c,JobType__c FROM NS_Sync_Request__c WHERE Id In: this.syncRecList ];
        }
    
        return new CustomNSSyncRequestIterator(syncRequestList);
    }
}