force-app/main/default/objects/Connector_Configurations__c/Connector_Configurations__c.object-meta.xml
<CustomObject>
    <label>Connector Configuration</label>
    <nameField>
        <displayFormat>Config-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Connector Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Connector_Configurations__c/fields/Enable_Sync__c.field-meta.xml
<CustomField>
    <fullName>Enable_Sync__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enable Sync</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Connector_Configurations__c/fields/Netsuite_Instance__c.field-meta.xml
<CustomField>
    <fullName>Netsuite_Instance__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Select NetSuite sandbox or production environment.</description>
    <inlineHelpText>Select NetSuite sandbox or production environment.</inlineHelpText>
    <label>Netsuite Instance</label>
    <referenceTo>NS_Sandboxes__c</referenceTo>
    <relationshipLabel>Connector Configurations</relationshipLabel>
    <relationshipName>Connector_Configurations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Toggle_Sync_to_NS__c.field-meta.xml
<CustomField>
    <fullName>Toggle_Sync_to_NS__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Toggle Sync to NS</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Field_Mapping__c/Field_Mapping__c.object-meta.xml
<CustomObject>
    <label>Field Mapping</label>
    <nameField>
        <displayFormat>FM-{0000000}</displayFormat>
        <label>Field Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Field Mappings</pluralLabel>
    <!---->
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NS_Sandboxes__c/NS_Sandboxes__c.object-meta.xml
<CustomObject>
    <label>Instances</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NS_Scripts__c/NS_Scripts__c.object-meta.xml
<CustomObject>
    <label>NS Scripts</label>
    <nameField>
        <displayFormat>NS Script - {0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NS Scripts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NS_Scripts__c/fields/NS_Sandboxes__c.field-meta.xml
<CustomField>
    <fullName>NS_Sandboxes__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>NS Sandboxes</label>
    <referenceTo>NS_Sandboxes__c</referenceTo>
    <relationshipName>NS_Sync_Scripts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NS_Scripts__c/fields/Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Name__c</fullName>
    <inlineHelpText>Object API Name E.g. Account, CustomObject__C</inlineHelpText>
    <label>Object Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NS_Scripts__c/fields/Script_URL__c.field-meta.xml
<CustomField>
    <fullName>Script_URL__c</fullName>
    <inlineHelpText>URL Format: ?script=1234&amp;deploy=1</inlineHelpText>
    <label>Script URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/NS_Sync_Request__c/NS_Sync_Request__c.object-meta.xml
<CustomObject>
    <label>Sync Request</label>
    <nameField>
        <displayFormat>NSR-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sync Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NS_Sync_Request__c/fields/Source_Object_Type__c.field-meta.xml
<CustomField>
    <fullName>Source_Object_Type__c</fullName>
    <description>Type of the record&apos;s object that needs to be synced E.g. Account, Order, Invoice etc....</description>
    <inlineHelpText>Type of the record&apos;s object that needs to be synced E.g. Account, Order, Invoice etc....</inlineHelpText>
    <label>Source Object Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NS_Sync_Request__c/fields/Source_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Source_Record_Id__c</fullName>
    <description>Id object the record that needs to be synced to Netsuite.</description>
    <inlineHelpText>Id object the record that needs to be synced to Netsuite.</inlineHelpText>
    <label>Source Record Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NS_Sync_Request__c/fields/Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>Sync_Status__c</fullName>
    <label>Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In-Progress</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
            </value>
            <value>
                <fullName>Queued</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
                <isActive>false</isActive>
                <label>Accepted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Toggle_Sync_to_NS__c.field-meta.xml
<CustomField>
    <fullName>Toggle_Sync_to_NS__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Toggle Sync to NS</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Toggle_Sync_to_NS__c.field-meta.xml
<CustomField>
    <fullName>Toggle_Sync_to_NS__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Toggle Sync to NS</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Toggle_Sync_to_NS__c.field-meta.xml
<CustomField>
    <fullName>Toggle_Sync_to_NS__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Toggle Sync to NS</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SObject_Mapping__c/SObject_Mapping__c.object-meta.xml
<CustomObject>
    <label>JSON Mapping</label>
    <nameField>
        <label>SObject Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>JSON Mapping</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SObject_Mapping__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>True: to sync records of the object mentioned in SObject Name using Netsuite Connector App.
False: to stop sync records of the object mentioned in SObject Name using Netsuite Connector App.</inlineHelpText>
    <label>IsActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SObject_Mapping__c/fields/JSON_Sobject_Name__c.field-meta.xml
<CustomField>
    <fullName>JSON_Sobject_Name__c</fullName>
    <inlineHelpText>Required. SObject identifier in the NetSuite.</inlineHelpText>
    <label>JSON SObject Name</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/SObject_Mapping__c/fields/Parent_SObject_Map__c.field-meta.xml
<CustomField>
    <fullName>Parent_SObject_Map__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Required for child Relationship Type.
Lookup to parent object.</inlineHelpText>
    <label>Parent SObject Map</label>
    <referenceTo>SObject_Mapping__c</referenceTo>
    <relationshipLabel>SObject Mapping</relationshipLabel>
    <relationshipName>SObject_Mappings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SObject_Mapping__c/fields/Relationship_Type__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Type__c</fullName>
    <inlineHelpText>Parent: use for parent object. E.g. Opportunity
Child: use for child object. E.g. OpportunityContactRole / OpportunityLineItem</inlineHelpText>
    <label>Relationship Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Parent</fullName>
            </value>
            <value>
                <fullName>Child</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SObject_Mapping__c/fields/Relationship_with_parent__c.field-meta.xml
<CustomField>
    <fullName>Relationship_with_parent__c</fullName>
    <inlineHelpText>Required for child Relationship Type. 
API name of the parent object relationship field (Lookup / Master-Details) on object mentioned in Parent SObject Mapping field. 
E.g. If SObject Name is OpportunityLineItem then OpportunityId or any other custom lookup or master detail field referencing Opportunity.</inlineHelpText>
    <label>Relationship with parent</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/NSSyncRequestTestClass.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 04-02-2024
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
@isTest
public class NSSyncRequestTestClass {
    @isTest static void syncAccounttoNS(){
        NS_Sandboxes__c inst = new NS_Sandboxes__c();
        inst.Name = 'demo sandbox';
        inst.End_Point_URL__c = 'https://td2345/restlet.api';
        insert inst;
        
        NS_Scripts__c script = new NS_Scripts__c(
            Object_Name__c = 'Account',
            NS_Sandboxes__c = inst.id,
            Script_URL__c = '?script=1595&deploy=1'
        );
        insert script;

        Connector_Configurations__c config = new Connector_Configurations__c();
        config.Enable_Sync__c = true;
        config.Netsuite_Instance__c = inst.id;
        insert config;
        
        SObject_Mapping__c sobj = new SObject_Mapping__c();
        sobj.IsActive__c = true;
        sobj.JSON_Sobject_Name__c = 'Customer';
        sobj.Name = 'Account';
        insert sobj;
        
        List<Field_Mapping__c> fieldMList = new List<Field_Mapping__c>();
        Field_Mapping__c fieldM = new Field_Mapping__c(
            SObject_Mapping__c=sobj.id,
            Field_Type__c = 'URL',
            NetSuite_Field_API_Name__c = 'url', 
            SFDC_Field_API_Name__c = 'Website' 
        );
        fieldMList.add(fieldM);
        Field_Mapping__c fieldM1 = new Field_Mapping__c(
            SObject_Mapping__c=sobj.id,
            Field_Type__c = 'Text',
            NetSuite_Field_API_Name__c = 'custentity_external_id', 
            SFDC_Field_API_Name__c = 'Id' 
        );
        fieldMList.add(fieldM1);
        Field_Mapping__c fieldM2 = new Field_Mapping__c(
            SObject_Mapping__c=sobj.id,
            Field_Type__c = 'Text',
            NetSuite_Field_API_Name__c = 'companyname', 
            SFDC_Field_API_Name__c = 'Name' 
        );
        fieldMList.add(fieldM2);
        Field_Mapping__c fieldM3 = new Field_Mapping__c(
            SObject_Mapping__c=sobj.id,
            Field_Type__c = 'Text',
            NetSuite_Field_API_Name__c = 'phone', 
            SFDC_Field_API_Name__c = 'phone' 
        );
        fieldMList.add(fieldM3);
        Field_Mapping__c fieldM4 = new Field_Mapping__c(
            SObject_Mapping__c=sobj.id,
            Field_Type__c = 'Text',
            NetSuite_Field_API_Name__c = 'Country', 
            SFDC_Field_API_Name__c = 'BillingCountry' 
        );
        fieldMList.add(fieldM4);
        insert fieldMList;

        Test.startTest();
            Test.setMock(HttpCalloutMock.class, new MockWebserviceClass_Test());
            Account testAccount = new Account(Name = 'Test Account');
            testAccount.Toggle_Sync_to_NS__c = true;
            insert testAccount;
        Test.stopTest();
        
    }
    
    @isTest static void syncOpportunitytoNS(){
      
        NS_Sandboxes__c inst = new NS_Sandboxes__c();
        inst.Name = 'demo sandbox';
        inst.End_Point_URL__c = 'https://td2345/restlet.api';
        insert inst;
        
        NS_Scripts__c script = new NS_Scripts__c(
            Object_Name__c = 'Opportunity',
            NS_Sandboxes__c = inst.id,
            Script_URL__c = '?script=1595&deploy=1'
        );
        insert script;

        Connector_Configurations__c config = new Connector_Configurations__c();
        config.Enable_Sync__c = true;
        config.Netsuite_Instance__c = inst.id;
        insert config;
        
        SObject_Mapping__c sobj = new SObject_Mapping__c();
        sobj.IsActive__c = true;
        sobj.JSON_Sobject_Name__c = 'Sales Order';
        sobj.Name = 'Opportunity';
        insert sobj;

        SObject_Mapping__c sobj1 = new SObject_Mapping__c();
        sobj1.IsActive__c = true;
        sobj1.JSON_Sobject_Name__c = 'OpportunityLineItem';
        sobj1.Name = 'OpportunityLineItem';
        sobj1.Parent_SObject_Map__c = sobj.id;
        sobj1.Relationship_Type__c = 'Child';
        sobj1.Relationship_with_parent__c   = 'OpportunityId';
        insert sobj1;

        List<Field_Mapping__c> fieldMList = new List<Field_Mapping__c>();
        Field_Mapping__c fieldM = new Field_Mapping__c(
            SObject_Mapping__c=sobj.id,
            Field_Type__c = 'URL',
            NetSuite_Field_API_Name__c = 'amount', 
            SFDC_Field_API_Name__c = 'Amount',
            IsActive__c = true
        );
        fieldMList.add(fieldM);

        Field_Mapping__c fieldM2 = new Field_Mapping__c(
            SObject_Mapping__c=sobj.id,
            Field_Type__c = 'URL',
            NetSuite_Field_API_Name__c = 'custbody_salesforce_ext_id', 
            SFDC_Field_API_Name__c = 'Id' ,
            IsActive__c = true
        );
        fieldMList.add(fieldM2);

        Field_Mapping__c fieldM3 = new Field_Mapping__c(
            SObject_Mapping__c=sobj.id,
            Field_Type__c = 'URL',
            NetSuite_Field_API_Name__c = 'opportunity', 
            SFDC_Field_API_Name__c = 'Name',
            IsActive__c = true 
        );
        fieldMList.add(fieldM3);

        Field_Mapping__c fieldM4 = new Field_Mapping__c(
            SObject_Mapping__c=sobj.id,
            Field_Type__c = 'URL',
            NetSuite_Field_API_Name__c = 'entity', 
            SFDC_Field_API_Name__c = 'AccountId' ,
            IsActive__c = true
        );
        fieldMList.add(fieldM4);

        Field_Mapping__c fieldM5 = new Field_Mapping__c(
            SObject_Mapping__c=sobj1.id,
            Field_Type__c = 'Number',
            NetSuite_Field_API_Name__c = 'rate', 
            SFDC_Field_API_Name__c = 'UnitPrice',
            IsActive__c = true
        );
        fieldMList.add(fieldM5);

        Field_Mapping__c fieldM6 = new Field_Mapping__c(
            SObject_Mapping__c=sobj1.id,
            Field_Type__c = 'Text',
            NetSuite_Field_API_Name__c = 'custitem_salesforce_prd_id', 
            SFDC_Field_API_Name__c = 'Product2Id',
            IsActive__c = true
        );
        fieldMList.add(fieldM6);
        Field_Mapping__c fieldM7 = new Field_Mapping__c(
            SObject_Mapping__c=sobj1.id,
            Field_Type__c = 'Text',
            NetSuite_Field_API_Name__c = 'displayname', 
            SFDC_Field_API_Name__c = 'Name' ,
            IsActive__c = true
        );
        fieldMList.add(fieldM7);
        Field_Mapping__c fieldM8 = new Field_Mapping__c(
            SObject_Mapping__c=sobj1.id,
            Field_Type__c = 'Text',
            NetSuite_Field_API_Name__c = 'custcol_leid', 
            SFDC_Field_API_Name__c = 'Id' ,
            IsActive__c = true
        );
        fieldMList.add(fieldM8);
        Field_Mapping__c fieldM9 = new Field_Mapping__c(
            SObject_Mapping__c=sobj1.id,
            Field_Type__c = 'Text',
            NetSuite_Field_API_Name__c = 'quantity', 
            SFDC_Field_API_Name__c = 'Quantity' ,
            IsActive__c = true
        );
        fieldMList.add(fieldM9);
        insert fieldMList;
        
       

        Account acc = new Account(Name = 'Test Account');
        insert acc;

        Opportunity testOpp = new Opportunity(Name = 'Test Oppo');
        testOpp.StageName = 'Closed Won';
        testOpp.AccountId = acc.Id;
        testOpp.CloseDate = System.today();
        testOpp.Toggle_Sync_to_NS__c = false;
        insert testOpp;

        Product2 prod2 = new Product2(
            Name = 'testName',
            IsActive=true);
        insert prod2;
        
        PricebookEntry price = new PricebookEntry(
            UseStandardPrice = false,
            Pricebook2Id = test.getStandardPricebookId(),
            UnitPrice = 1.0,
            IsActive = true,
            Product2Id = prod2.Id);
        insert price;
        
        OpportunityLineItem oli = new OpportunityLineItem(opportunityId = testOpp.Id,quantity=2,unitprice=20,PricebookEntryId =price.id );
        insert oli;

        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new MockWebserviceClass_Test());
            Opportunity opp = [Select id,Toggle_Sync_to_NS__c,AccountId,StageName,CloseDate From Opportunity where Name = 'Test Oppo'];
            opp.Toggle_Sync_to_NS__c = true;
            opp.StageName = 'Closed Lost';
            update opp;
        Test.stopTest();

    }
    @isTest
    static void syncContacttoNS(){
        Test.startTest();
        Contact newContact = new Contact(FirstName = 'New', LastName = 'Contact');
        insert newContact;
        Test.stopTest();
    }

    @isTest
    static void serializeAddressTest(){

        Account acct = new Account(name = 'TestAccount', BillingStreet='xyz',BillingCity = 'Pune', BillingState = 'Maharashtra', BillingCountry = 'India' , Billingpostalcode = '1234');
        NSSyncService.serializeAddress(acct,'Billing');

        Account acct2 = new Account(name = 'TestAccount', ShippingStreet='xyz',ShippingCity = 'Pune', ShippingState = 'Maharashtra', ShippingCountry = 'India' , Shippingpostalcode = '1234');
        NSSyncService.serializeAddress(acct2,'Shipping');
    
        Contact cont = new Contact(FirstName = 'Test', LastName = 'Contact', MailingStreet = 'xyz',MailingCity = 'Pune',MailingState = 'Maharashtra',MailingCountry = 'India',Mailingpostalcode = '1234');
        NSSyncService.serializeAddress(cont,'Mailing');

        Contact cont1 = new Contact(FirstName = 'Test', LastName = 'Contact', OtherStreet = 'xyz',OtherCity = 'Pune',OtherState = 'Maharashtra',OtherCountry = 'India',Otherpostalcode = '1234');
        NSSyncService.serializeAddress(cont1,'other');
    
    }

    @isTest
    static void syncRequestBatchSchedulerTest(){
        Test.startTest();
        NSSyncRequestBatchScheduler scheduler = new NSSyncRequestBatchScheduler('Account');
        scheduler.execute(null);
        Test.stopTest();
    }


    @isTest
    static void SyncRequestErrorTest(){
        Test.startTest();
        TriggerServiceHandler handler = new TriggerServiceHandler();
        NS_Sync_Request__c req = new NS_Sync_Request__c(
            Source_Record_Id__c = '012365478912365',
            Source_Object_Type__c = 'Account',
            Sync_Status__c = 'Queueddd'
        );
        handler.creatNSSyncRequests(new List<NS_Sync_Request__c>{req});
        Test.stopTest();
    }

    @isTest
    static void syncRequestHandler(){
        NSSyncRequestTriggerServiceImpl req= new NSSyncRequestTriggerServiceImpl();
        req.beforeInsert();
        req.beforeUpdate();
        req.beforeDelete();
        req.afterUpdate();
        req.afterDelete();
        req.afterUndelete();
    }
}