force-app/main/default/objects/Connector_Configurations__c/Connector_Configurations__c.object-meta.xml
<CustomObject>
    <label>Connector Configuration</label>
    <nameField>
        <displayFormat>Config-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Connector Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Connector_Configurations__c/fields/Enable_Sync__c.field-meta.xml
<CustomField>
    <fullName>Enable_Sync__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enable Sync</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Connector_Configurations__c/fields/JSON_Mapping__c.field-meta.xml
<CustomField>
    <fullName>JSON_Mapping__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked while enabling sync and field mapping is added in the field mapping object.</description>
    <inlineHelpText>Checked while enabling sync and field mapping is added in the field mapping object.</inlineHelpText>
    <label>JSON Mapping</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Connector_Configurations__c/fields/Netsuite_Instance__c.field-meta.xml
<CustomField>
    <fullName>Netsuite_Instance__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Select NetSuite sandbox or production environment.</description>
    <inlineHelpText>Select NetSuite sandbox or production environment.</inlineHelpText>
    <label>Netsuite Instance</label>
    <referenceTo>NS_Sandboxes__c</referenceTo>
    <relationshipLabel>Connector Configurations</relationshipLabel>
    <relationshipName>Connector_Configurations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Connector_Configurations__c/fields/NS_Requests_Delete_Days__c.field-meta.xml
<CustomField>
    <fullName>NS_Requests_Delete_Days__c</fullName>
    <description>Based this field value NS Requests will be pulled in the Delete NS Requests batch process.</description>
    <inlineHelpText>Based on the number of days (n) provided system will delete the NS Requests records created which are (n) days ago.</inlineHelpText>
    <label>NS Requests Delete Days</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Connector_Configurations__c/fields/Schedule__c.field-meta.xml
<CustomField>
    <fullName>Schedule__c</fullName>
    <description>Holds the Cron expression.</description>
    <inlineHelpText>Default Cron Expression: 0 0 0 * * ?</inlineHelpText>
    <label>Schedule Preference</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Connector_Configurations__c/fields/Schedule_Delete_Job__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Delete_Job__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Schedule Delete Job</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ConnectorConfigurationsClass.cls
/**
 * @description       : Sigleton pattern class to provide connector configuration details which will be accessed using class property.
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 03-29-2024
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public with sharing class ConnectorConfigurationsClass {
    //In singleton pattern instantiation to null is required otherwise singleton doesn't work
    private static ConnectorConfigurationsClass connectorConfig = null;
    public Connector_Configurations__c config;
    private ConnectorConfigurationsClass() {
        getConfigurations();
    }


    /**
    * @description : Singleton pattern to instantiate class and its members
    * @author ChangeMeIn@UserSettingsUnder.SFDoc | 02-23-2024 
    * @return ConnectorConfigurationsClass 
    **/
    public static ConnectorConfigurationsClass getInstance(){
        if(connectorConfig == null){
            connectorConfig = new ConnectorConfigurationsClass();
        }
        return connectorConfig;
    }

    /**
    * @description : Fetch Connector_Configurations__c details which will be used to know which actions are allowed and which are not allowed
    * @author ChangeMeIn@UserSettingsUnder.SFDoc | 02-23-2024 
    **/
    public void getConfigurations(){
        List<Connector_Configurations__c> configList = new List<Connector_Configurations__c>([SELECT id,Enable_Sync__c,JSON_Mapping__c,Netsuite_Instance__c,NS_Requests_Delete_Days__c,Schedule_Delete_Job__c,Schedule__c FROM Connector_Configurations__c order by createddate Asc Limit 1]);
        if(!configList.isEmpty()){
            config = configList.get(0);
        }
       
    }

}