force-app/main/default/objects/Connector_Configurations__c/Connector_Configurations__c.object-meta.xml
<CustomObject>
    <label>Connector Configuration</label>
    <nameField>
        <displayFormat>Config-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Connector Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Connector_Configurations__c/fields/Enable_Sync__c.field-meta.xml
<CustomField>
    <fullName>Enable_Sync__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enable Sync</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Connector_Configurations__c/fields/Netsuite_Instance__c.field-meta.xml
<CustomField>
    <fullName>Netsuite_Instance__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Select NetSuite sandbox or production environment.</description>
    <inlineHelpText>Select NetSuite sandbox or production environment.</inlineHelpText>
    <label>Netsuite Instance</label>
    <referenceTo>NS_Sandboxes__c</referenceTo>
    <relationshipLabel>Connector Configurations</relationshipLabel>
    <relationshipName>Connector_Configurations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NS_Sandboxes__c/NS_Sandboxes__c.object-meta.xml
<CustomObject>
    <label>Instances</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NS_Sync_Request__c/NS_Sync_Request__c.object-meta.xml
<CustomObject>
    <label>Sync Request</label>
    <nameField>
        <displayFormat>NSR-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sync Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DeleteNetsuiteSyncRequestsTest.cls
/**
* @description       : 
* @author            : ChangeMeIn@UserSettingsUnder.SFDoc
* @group             : 
* @last modified on  : 03-21-2024
* @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
@isTest
public class DeleteNetsuiteSyncRequestsTest {
    
    @isTest
    static void testStartMethod() {
        // Test setup
        NS_Sandboxes__c inst = new NS_Sandboxes__c();
        inst.Name = 'demo sandbox';
        inst.End_Point_URL__c = 'https://td2345/restlet.api';
        insert inst;
        
        Connector_Configurations__c config = new Connector_Configurations__c();
        config.Enable_Sync__c = true;
        config.Netsuite_Instance__c = inst.id;
        insert config;
        
        
        // Call the start method
        Test.startTest();
        DeleteNetsuiteSyncRequests batchClass = new DeleteNetsuiteSyncRequests();
        Database.QueryLocator queryLocator = batchClass.start(null);
        Test.stopTest();
    }
    
    @isTest
    static void testExecuteMethod() {
        // Call the execute method
        Test.startTest();
        DeleteNetsuiteSyncRequests batchClass = new DeleteNetsuiteSyncRequests();
        batchClass.execute(null, new List<NS_Sync_Request__c>());
        Test.stopTest();
    }
    
    @isTest
    static void testFinishMethod() {
        // Test the finish method
        Test.startTest();
        DeleteNetsuiteSyncRequests batchClass = new DeleteNetsuiteSyncRequests();
        batchClass.finish(null);
        Test.stopTest();
    }
    
    @isTest
    static void testSchedulableMethod() {
        // Test the schedulable method
        Test.startTest();
        DeleteNetsuiteSyncRequests batchClass = new DeleteNetsuiteSyncRequests();
        batchClass.execute(null);
        Test.stopTest();
    }
}