force-app/main/default/objects/Connector_Configurations__c/Connector_Configurations__c.object-meta.xml
<CustomObject>
    <label>Connector Configuration</label>
    <nameField>
        <displayFormat>Config-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Connector Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Connector_Configurations__c/fields/Enable_Sync__c.field-meta.xml
<CustomField>
    <fullName>Enable_Sync__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enable Sync</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Connector_Configurations__c/fields/Netsuite_Instance__c.field-meta.xml
<CustomField>
    <fullName>Netsuite_Instance__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Select NetSuite sandbox or production environment.</description>
    <inlineHelpText>Select NetSuite sandbox or production environment.</inlineHelpText>
    <label>Netsuite Instance</label>
    <referenceTo>NS_Sandboxes__c</referenceTo>
    <relationshipLabel>Connector Configurations</relationshipLabel>
    <relationshipName>Connector_Configurations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NS_Sandboxes__c/NS_Sandboxes__c.object-meta.xml
<CustomObject>
    <label>Instances</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SObject_Mapping__c/SObject_Mapping__c.object-meta.xml
<CustomObject>
    <label>JSON Mapping</label>
    <nameField>
        <label>SObject Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>JSON Mapping</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SObject_Mapping__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>True: to sync records of the object mentioned in SObject Name using Netsuite Connector App.
False: to stop sync records of the object mentioned in SObject Name using Netsuite Connector App.</inlineHelpText>
    <label>IsActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SObject_Mapping__c/fields/JSON_Sobject_Name__c.field-meta.xml
<CustomField>
    <fullName>JSON_Sobject_Name__c</fullName>
    <inlineHelpText>Required. SObject identifier in the NetSuite.</inlineHelpText>
    <label>JSON SObject Name</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/NSSyncQuickActionHandlerTest.cls
/**
* @description       : 
* @author            : ChangeMeIn@UserSettingsUnder.SFDoc
* @group             : 
* @last modified on  : 03-21-2024
* @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
@isTest
public class NSSyncQuickActionHandlerTest {
    
    @isTest
    static void testCreateNSSyncRequest() {
        // Test data setup
        NS_Sandboxes__c inst = new NS_Sandboxes__c();
        inst.Name = 'demo sandbox';
        inst.End_Point_URL__c = 'https://td2345/restlet.api';
        insert inst;
        
        Connector_Configurations__c config = new Connector_Configurations__c();
        config.Enable_Sync__c = true;
        config.Netsuite_Instance__c = inst.id;
        insert config;
        
        SObject_Mapping__c sobj = new SObject_Mapping__c();
        sobj.IsActive__c = true;
        sobj.JSON_Sobject_Name__c = 'customer';
        sobj.Name = 'Account';
        insert sobj;
        
        Account acc = new Account();
        acc.Toggle_Sync_to_NS__c = true;
        acc.Name = 'Test Account';
        insert acc;
        
        NSSyncQuickActionHandler.inputParams input = new NSSyncQuickActionHandler.inputParams();
        input.recordId = acc.Id;
        input.userSyncConfirmation = false;
        List<NSSyncQuickActionHandler.inputParams> inputList = new List<NSSyncQuickActionHandler.inputParams>();
        inputList.add(input);
        
        // Test method execution
        Test.startTest();
        List<NSSyncQuickActionHandler.outputParams> resultList = NSSyncQuickActionHandler.createNSSyncRequest(inputList);
        Test.stopTest();
        
        // Assert results
        System.assertEquals(1, resultList.size(), 'Result list should contain one item');
        NSSyncQuickActionHandler.outputParams output = resultList[0];
        //System.assert(output.isCreaateSuccess != null, 'isCreaateSuccess should not be null');
        
    }
    
}